config/routes.rb
Rails.application.routes.draw do
  resources :cargos
  resources :movimientos
  root to: 'personals#index'
  resources :personals
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cargo.rb
class Cargo < ApplicationRecord
  belongs_to :personal
  validates :hasta, :desde, presence: true
end

app/models/movimiento.rb
class Movimiento < ApplicationRecord
  belongs_to :personal
  validates :fecha_hasta, :fecha_desde, presence: true

end

app/models/personal.rb
class Personal < ApplicationRecord
  has_many :movimientos
  validates :documento, :apeynom, :fecnac, :fecing, presence: true
  def apeynom=(s)
    write_attribute(:apeynom, s.to_s.titleize) # The to_s is in case you get nil/non-string
  end
  def self.search(search)
    where("apeynom ILIKE ?", "%#{search}%")
    #where("content LIKE ?", "%#{search}%")
  end
  has_many :cargos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:personal_id, :cargo, :desde, :hasta, :curso, :activo)
    end
end

app/controllers/movimientos_controller.rb
class MovimientosController < ApplicationController
  before_action :set_movimiento, only: [:show, :edit, :update, :destroy]

  # GET /movimientos
  # GET /movimientos.json
  def index
    @movimientos = Movimiento.all
  end

  # GET /movimientos/1
  # GET /movimientos/1.json
  def show
  end

  # GET /movimientos/new
  def new
    @movimiento = Movimiento.new
  end

  # GET /movimientos/1/edit
  def edit
  end

  # POST /movimientos
  # POST /movimientos.json
  def create
    @movimiento = Movimiento.new(movimiento_params)

    respond_to do |format|
      if @movimiento.save
        format.html { redirect_to @movimiento, notice: 'Se creó el registro con éxito.' }
        format.json { render :show, status: :created, location: @movimiento }
      else
        format.html { render :new }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimientos/1
  # PATCH/PUT /movimientos/1.json
  def update
    respond_to do |format|
      if @movimiento.update(movimiento_params)
        format.html { redirect_to @movimiento, notice: 'La actualización fue exitosa.' }
        format.json { render :show, status: :ok, location: @movimiento }
      else
        format.html { render :edit }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimientos/1
  # DELETE /movimientos/1.json
  def destroy
    @movimiento.destroy
    respond_to do |format|
      format.html { redirect_to movimientos_url, notice: 'Movimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimiento
      @movimiento = Movimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movimiento_params
      params.require(:movimiento).permit(:personal_id, :fecha_desde, :fecha_hasta, :motivo, :con_aviso, :justificado)
    end
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_personal, only: [:show, :edit, :update, :destroy]

  # GET /personals
  # GET /personals.json
  def index
    @personals = Personal.all.order("apeynom ASC")
    if params[:search]
      @personals = Personal.search(params[:search]).order('apeynom ASC')
    else
      @personals = Personal.all.order('apeynom ASC')
    end
  end

  # GET /personals/1
  # GET /personals/1.json
  def show
  end

  # GET /personals/new
  def new
    @personal = Personal.new
  end

  # GET /personals/1/edit
  def edit
  end

  # POST /personals
  # POST /personals.json
  def create
    @personal = Personal.new(personal_params)

    respond_to do |format|
      if @personal.save
        format.html { redirect_to @personal, notice: 'Se creó el registro con éxito.' }
        format.json { render :show, status: :created, location: @personal }
      else
        format.html { render :new }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personals/1
  # PATCH/PUT /personals/1.json
  def update
    respond_to do |format|
      if @personal.update(personal_params)
        format.html { redirect_to @personal, notice: 'La actualización fue exitosa.' }
        format.json { render :show, status: :ok, location: @personal }
      else
        format.html { render :edit }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personals/1
  # DELETE /personals/1.json
  def destroy
    @personal.destroy
    respond_to do |format|
      format.html { redirect_to personals_url, notice: 'Personal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal
      @personal = Personal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_params
      params.require(:personal).permit(:documento, :apeynom, :fecnac, :fecing, :domic, :activo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/inasistencia_helper.rb
module InasistenciaHelper
end

app/helpers/movimientos_helper.rb
module MovimientosHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/views/cargos/_form.html.erb
<%= simple_form_for(@cargo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :personal, :label_method => :apeynom %>
    <%= f.input :cargo %>
    <%= f.input :desde %>
    <%= f.input :hasta %>
    <%= f.input :curso %>
    <%= f.input :activo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Personal</th>
      <th>Cargo</th>
      <th>Desde</th>
      <th>Hasta</th>
      <th>Curso</th>
      <th>Activo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.personal_id %></td>
        <td><%= cargo.cargo %></td>
        <td><%= cargo.desde %></td>
        <td><%= cargo.hasta %></td>
        <td><%= cargo.curso %></td>
        <td><%= cargo.activo %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Personal:</strong>
  <%= @cargo.personal.apeynom %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @cargo.cargo %>
</p>

<p>
  <strong>Desde:</strong>
  <%= @cargo.desde %>
</p>

<p>
  <strong>Hasta:</strong>
  <%= @cargo.hasta %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @cargo.curso %>
</p>

<p>
  <strong>Activo:</strong>
  <%= @cargo.activo %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asistencia</title>
    <center><h1>ESCUELA PREUNIVERSITARIA "FRAY MAMERTO ESQUIÚ"</h1></center>
    <center><h2>Sistema de Gestión de Secretaría</h2></center>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= image_tag("universidad.jpg", size: "300x150", class: "img-responsive center-block")  %>
   <!--
    <img src=".jpg" alt="" width="300" height="150" />
    -->
  </head>

  <body>
  <body style="background-color:#FFC300;">

    <%= yield %>
  </body>
</html>

app/views/movimientos/_form.html.erb
<%= simple_form_for(@movimiento) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :personal, :label_method => :apeynom %>
    <%= f.input :fecha_desde %>
    <%= f.input :fecha_hasta %>
    <%= f.input :motivo %>
    <%= f.input :con_aviso %>
    <%= f.input :justificado %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/movimientos/edit.html.erb
<h1>Editing Movimiento</h1>

<%= render 'form', movimiento: @movimiento %>

<%= link_to 'Show', @movimiento %> |
<%= link_to 'Back', movimientos_path %>

app/views/movimientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movimientos</h1>

<table>
  <thead>
    <tr>
      <th>Personal</th>
      <th>Fecha desde</th>
      <th>Fecha hasta</th>
      <th>Motivo</th>
      <th>Con aviso</th>
      <th>Justificado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movimientos.each do |movimiento| %>
      <tr>
        <td><%= movimiento.personal.apeynom %></td>
        <td><%= movimiento.fecha_desde %></td>
        <td><%= movimiento.fecha_hasta %></td>
        <td><%= movimiento.motivo %></td>
        <td><%= movimiento.con_aviso %></td>
        <td><%= movimiento.justificado %></td>
        <td><%= link_to 'Mostrar', movimiento %>|</td>
        <td><%= link_to 'Editar', edit_movimiento_path(movimiento) %>|</td>
        <td><%= link_to 'Eliminar', movimiento, method: :delete, data: { confirm: 'Confirma?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movimiento', new_movimiento_path %>
<%= link_to 'Personal', personals_path %>

app/views/movimientos/new.html.erb
<h1>New Movimiento</h1>

<%= render 'form', movimiento: @movimiento %>

<%= link_to 'Back', movimientos_path %>

app/views/movimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Personal:</strong>
  <%= @movimiento.personal.apeynom %>
</p>

<p>
  <strong>Fecha desde:</strong>
  <%= @movimiento.fecha_desde %>
</p>

<p>
  <strong>Fecha hasta:</strong>
  <%= @movimiento.fecha_hasta %>
</p>

<p>
  <strong>Motivo:</strong>
  <%= @movimiento.motivo %>
</p>

<p>
  <strong>Con aviso:</strong>
  <%= @movimiento.con_aviso %>
</p>

<p>
  <strong>Justificado:</strong>
  <%= @movimiento.justificado %>
</p>

<%= link_to 'Edit', edit_movimiento_path(@movimiento) %> |
<%= link_to 'Back', movimientos_path %>

app/views/personals/_form.html.erb
<%= simple_form_for(@personal) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :documento, label:'Documento' %>
    <%= f.input :apeynom, label:'Apellido y nombres' %>
    <%= f.input :fecnac, label:'Fecha de nacimiento',
    start_year: Date.today.year - 70, end_year: Date.today.year %>
    <%= f.input :fecing, label:'Fecha de ingreso', start_year: Date.today.year - 40,
     end_year: Date.today.year %>
    <%= f.input :domic, label:'Domicilio' %>
    <%= f.input :activo, label:'Activo', as: :radio_buttons %>

  </div>

  <div class="form-actions">
    <%= f.button :submit,label:'Enviar' %>
  </div>
<% end %>

app/views/personals/edit.html.erb
<h1>Editing Personal</h1>

<%= render 'form', personal: @personal %>

<%= link_to 'Mostrar', @personal %> |
<%= link_to 'Volver', personals_path %>

app/views/personals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal</h1>
<%= form_tag(personals_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Búsqueda de agente" %>
<%= submit_tag "Search" %>
<% end %>
<% if @personals.present? %>
  
  <% else %>
  <p>Agente no encontrado <%= params[:search] %>.</p>
<% end %>
<table>
  <thead>
    <tr>
      <th>Documento</th>
      <th> Apellido y Nombres </th>
      <th> Fecha de Nacimiento </th>
      <th> Fecha de Ingreso </th>
      <th> Domicilio </th>
      <th> Activo </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personals.each do |personal| %>
      <tr>
        <td><%= personal.documento %></td>
        <td><%= personal.apeynom %></td>
        <td><%= personal.fecnac %></td>
        <td><%= personal.fecing %></td>
        <td><%= personal.domic %></td>
        <td><%= personal.activo %></td>
        <td><%= link_to 'Mostrar', personal %>|</td>
        <td><%= link_to 'Editar', edit_personal_path(personal) %>|</td>
        <td><%= link_to 'Eliminar', personal, method: :delete, data: { confirm: 'Confirma?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Agente', new_personal_path %>
<%= link_to 'Movimientos', movimientos_path %>

app/views/personals/new.html.erb
<h1>New Personal</h1>

<%= render 'form', personal: @personal %>

<%= link_to 'Back', personals_path %>

app/views/personals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Documento:</strong>
  <%= @personal.documento %>

  <strong>Apellido y nombres:</strong>
  <%= @personal.apeynom %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @personal.fecnac %>

  <strong>Fecha de ingreso:</strong>
  <%= @personal.fecing %>
</p>

<p>
  <strong>Domicilio:</strong>
  <%= @personal.domic %>

  <strong>Activo:</strong>
  <%= @personal.activo %>
</p>

<h4>Licencias del agente</h4>
<table>
  <thead>
    <tr>
      <th>Personal</th>
      <th>Fecha desde</th>
      <th>Fecha hasta</th>
      <th>Motivo</th>
      <th>Con aviso</th>
      <th>Justificado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal.movimientos.each do |movimiento| %>
      <tr>
        <td><%= movimiento.fecha_desde %></td>
        <td><%= movimiento.fecha_hasta %></td>
        <td><%= movimiento.motivo %></td>
        <td><%= movimiento.con_aviso %></td>
        <td><%= movimiento.justificado %></td>
        <td><%= link_to 'Mostrar', movimiento %></td>
        <td><%= link_to 'Editar', edit_movimiento_path(movimiento) %></td>
        <td><%= link_to 'Eliminar', movimiento, method: :delete, data: { confirm: 'Confirma?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Editar', edit_personal_path(@personal) %> |
<%= link_to 'Volver', personals_path %>